import type {
  CasePart,
  CoolerPart,
  CpuPart,
  GpuPart,
  MoboPart,
  Part,
  PsuPart,
  RamPart,
  SlotId,
  SsdPart,
} from "./types";

const cpus: CpuPart[] = [
  {
    id: "cpu-r5-7600",
    slot: "cpu",
    name: "Ryzen 5 7600",
    brand: "AMD",
    family: "AMD",
    priceUsd: 180,
    socket: "AM5",
    cores: 6,
    threads: 12,
    tdp: 65,
    igpu: true,
    gaming: 72,
    creator: 58,
    ai: 52,
    single: 78,
    blurb: "省電 6 核，適合 1080p 和文書。有堪用的內顯。",
  },
  {
    id: "cpu-r5-9600x",
    slot: "cpu",
    name: "Ryzen 5 9600X",
    brand: "AMD",
    family: "AMD",
    priceUsd: 230,
    socket: "AM5",
    cores: 6,
    threads: 12,
    tdp: 65,
    igpu: true,
    gaming: 78,
    creator: 64,
    ai: 56,
    single: 86,
    blurb: "Zen 5 六核。時脈快，還是 65 W。",
  },
  {
    id: "cpu-r7-7700",
    slot: "cpu",
    name: "Ryzen 7 7700",
    brand: "AMD",
    family: "AMD",
    priceUsd: 270,
    socket: "AM5",
    cores: 8,
    threads: 16,
    tdp: 65,
    igpu: true,
    gaming: 80,
    creator: 74,
    ai: 68,
    single: 80,
    blurb: "65 W 八核。中階創作夠用，不必大聲散熱。",
  },
  {
    id: "cpu-r7-7800x3d",
    slot: "cpu",
    name: "Ryzen 7 7800X3D",
    brand: "AMD",
    family: "AMD",
    priceUsd: 360,
    socket: "AM5",
    cores: 8,
    threads: 16,
    tdp: 120,
    igpu: true,
    gaming: 94,
    creator: 72,
    ai: 66,
    single: 82,
    blurb: "3D V-Cache 遊戲首選。全核輸出偏弱。",
  },
  {
    id: "cpu-r7-9800x3d",
    slot: "cpu",
    name: "Ryzen 7 9800X3D",
    brand: "AMD",
    family: "AMD",
    priceUsd: 480,
    socket: "AM5",
    cores: 8,
    threads: 16,
    tdp: 120,
    igpu: true,
    gaming: 100,
    creator: 78,
    ai: 70,
    single: 90,
    blurb: "目前遊戲王。為了打遊戲買，不是為了轉檔。",
  },
  {
    id: "cpu-r9-7900x",
    slot: "cpu",
    name: "Ryzen 9 7900X",
    brand: "AMD",
    family: "AMD",
    priceUsd: 340,
    socket: "AM5",
    cores: 12,
    threads: 24,
    tdp: 170,
    igpu: true,
    gaming: 82,
    creator: 88,
    ai: 82,
    single: 84,
    blurb: "12 核工作站力道。需要正經散熱。",
  },
  {
    id: "cpu-r9-9950x",
    slot: "cpu",
    name: "Ryzen 9 9950X",
    brand: "AMD",
    family: "AMD",
    priceUsd: 580,
    socket: "AM5",
    cores: 16,
    threads: 32,
    tdp: 170,
    igpu: true,
    gaming: 86,
    creator: 98,
    ai: 92,
    single: 92,
    blurb: "16 核旗艦，給 AI 前置、3D 和重輸出。",
  },
  {
    id: "cpu-i5-14600k",
    slot: "cpu",
    name: "Core i5-14600K",
    brand: "Intel",
    family: "Intel",
    priceUsd: 220,
    socket: "LGA1700",
    cores: 14,
    threads: 20,
    tdp: 125,
    igpu: true,
    gaming: 80,
    creator: 76,
    ai: 70,
    single: 84,
    blurb: "6P+8E 混合。上一代 Intel 的 1440p 好搭檔。",
  },
  {
    id: "cpu-i7-14700k",
    slot: "cpu",
    name: "Core i7-14700K",
    brand: "Intel",
    family: "Intel",
    priceUsd: 320,
    socket: "LGA1700",
    cores: 20,
    threads: 28,
    tdp: 125,
    igpu: true,
    gaming: 84,
    creator: 90,
    ai: 82,
    single: 86,
    blurb: "E-core 很多，編碼很猛。全核很燙。",
  },
  {
    id: "cpu-i9-14900k",
    slot: "cpu",
    name: "Core i9-14900K",
    brand: "Intel",
    family: "Intel",
    priceUsd: 430,
    socket: "LGA1700",
    cores: 24,
    threads: 32,
    tdp: 125,
    igpu: true,
    gaming: 86,
    creator: 94,
    ai: 86,
    single: 88,
    blurb: "14 代頂點。請準備 360 水冷和夠力的電源。",
  },
  {
    id: "cpu-u5-245k",
    slot: "cpu",
    name: "Core Ultra 5 245K",
    brand: "Intel",
    family: "Intel",
    priceUsd: 280,
    socket: "LGA1851",
    cores: 14,
    threads: 14,
    tdp: 125,
    igpu: true,
    gaming: 82,
    creator: 78,
    ai: 74,
    single: 88,
    blurb: "Arrow Lake 中階。新腳位，要 Z890／B860 板。",
  },
  {
    id: "cpu-u7-265k",
    slot: "cpu",
    name: "Core Ultra 7 265K",
    brand: "Intel",
    family: "Intel",
    priceUsd: 380,
    socket: "LGA1851",
    cores: 20,
    threads: 20,
    tdp: 125,
    igpu: true,
    gaming: 85,
    creator: 90,
    ai: 84,
    single: 90,
    blurb: "偏創作的 Arrow Lake。設計上沒有超執行緒。",
  },
  {
    id: "cpu-u9-285k",
    slot: "cpu",
    name: "Core Ultra 9 285K",
    brand: "Intel",
    family: "Intel",
    priceUsd: 550,
    socket: "LGA1851",
    cores: 24,
    threads: 24,
    tdp: 125,
    igpu: true,
    gaming: 88,
    creator: 96,
    ai: 88,
    single: 94,
    blurb: "Intel 現役桌機旗艦。主板和散熱不能省。",
  },
];

const gpus: GpuPart[] = [
  {
    id: "gpu-4060",
    slot: "gpu",
    name: "GeForce RTX 4060 8GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 280,
    vramGb: 8,
    tdp: 115,
    lengthMm: 242,
    gaming: 60,
    creator: 52,
    ai: 42,
    cuda: true,
    blurb: "1080p 卡。8 GB 顯存是本地 AI 的天花板。",
  },
  {
    id: "gpu-4060ti-16",
    slot: "gpu",
    name: "GeForce RTX 4060 Ti 16GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 430,
    vramGb: 16,
    tdp: 165,
    lengthMm: 244,
    gaming: 68,
    creator: 64,
    ai: 64,
    cuda: true,
    blurb: "光柵一般，16 GB 跑小模型很夠。",
  },
  {
    id: "gpu-4070s",
    slot: "gpu",
    name: "GeForce RTX 4070 Super 12GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 580,
    vramGb: 12,
    tdp: 220,
    lengthMm: 267,
    gaming: 78,
    creator: 74,
    ai: 58,
    cuda: true,
    blurb: "1440p 光柵甜點。12 GB 跑較大 LLM 偏緊。",
  },
  {
    id: "gpu-4070tis",
    slot: "gpu",
    name: "GeForce RTX 4070 Ti Super 16GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 780,
    vramGb: 16,
    tdp: 285,
    lengthMm: 305,
    gaming: 86,
    creator: 82,
    ai: 70,
    cuda: true,
    blurb: "高 1440p／入門 4K。16 GB 對創作和 AI 有幫助。",
  },
  {
    id: "gpu-4080s",
    slot: "gpu",
    name: "GeForce RTX 4080 Super 16GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 980,
    vramGb: 16,
    tdp: 320,
    lengthMm: 310,
    gaming: 90,
    creator: 88,
    ai: 74,
    cuda: true,
    blurb: "40 系能打 4K。卡很長，先量機殼。",
  },
  {
    id: "gpu-4090",
    slot: "gpu",
    name: "GeForce RTX 4090 24GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 1600,
    vramGb: 24,
    tdp: 450,
    lengthMm: 336,
    gaming: 96,
    creator: 96,
    ai: 88,
    cuda: true,
    blurb: "又大又餓，仍是本地 AI 主力。量兩次再買。",
  },
  {
    id: "gpu-5060",
    slot: "gpu",
    name: "GeForce RTX 5060 8GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 300,
    vramGb: 8,
    tdp: 145,
    lengthMm: 242,
    gaming: 66,
    creator: 56,
    ai: 44,
    cuda: true,
    blurb: "50 系入門。1080p 更快，還是 8 GB 顯存。",
  },
  {
    id: "gpu-5070",
    slot: "gpu",
    name: "GeForce RTX 5070 12GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 550,
    vramGb: 12,
    tdp: 250,
    lengthMm: 245,
    gaming: 82,
    creator: 76,
    ai: 60,
    cuda: true,
    blurb: "1440p 級、有新幀生成。12 GB 仍卡住 AI。",
  },
  {
    id: "gpu-5070ti",
    slot: "gpu",
    name: "GeForce RTX 5070 Ti 16GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 750,
    vramGb: 16,
    tdp: 300,
    lengthMm: 285,
    gaming: 90,
    creator: 86,
    ai: 72,
    cuda: true,
    blurb: "多數人真正要的 1440p／4K 萬用卡。",
  },
  {
    id: "gpu-5080",
    slot: "gpu",
    name: "GeForce RTX 5080 16GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 1000,
    vramGb: 16,
    tdp: 360,
    lengthMm: 304,
    gaming: 94,
    creator: 90,
    ai: 76,
    cuda: true,
    blurb: "準旗艦光柵。大模型會卡在顯存這顆星號。",
  },
  {
    id: "gpu-5090",
    slot: "gpu",
    name: "GeForce RTX 5090 32GB",
    brand: "NVIDIA",
    family: "NVIDIA",
    priceUsd: 2000,
    vramGb: 32,
    tdp: 575,
    lengthMm: 330,
    gaming: 100,
    creator: 100,
    ai: 98,
    cuda: true,
    blurb: "本地 AI 鐵槌。機殼、散熱、電源都要認真。",
  },
  {
    id: "gpu-rx7600",
    slot: "gpu",
    name: "Radeon RX 7600 8GB",
    brand: "AMD",
    family: "AMD",
    priceUsd: 250,
    vramGb: 8,
    tdp: 165,
    lengthMm: 204,
    gaming: 56,
    creator: 44,
    ai: 26,
    cuda: false,
    blurb: "又短又便宜的 1080p 卡。CUDA 路線的 AI 偏弱。",
  },
  {
    id: "gpu-rx7800xt",
    slot: "gpu",
    name: "Radeon RX 7800 XT 16GB",
    brand: "AMD",
    family: "AMD",
    priceUsd: 480,
    vramGb: 16,
    tdp: 263,
    lengthMm: 267,
    gaming: 76,
    creator: 62,
    ai: 46,
    cuda: false,
    blurb: "光柵性價比。ROCm 本地 AI 做得到，不好做。",
  },
  {
    id: "gpu-rx7900xtx",
    slot: "gpu",
    name: "Radeon RX 7900 XTX 24GB",
    brand: "AMD",
    family: "AMD",
    priceUsd: 780,
    vramGb: 24,
    tdp: 355,
    lengthMm: 287,
    gaming: 88,
    creator: 78,
    ai: 62,
    cuda: false,
    blurb: "沒有 CUDA，24 GB 仍能幫忙跑大模型。",
  },
  {
    id: "gpu-rx9070xt",
    slot: "gpu",
    name: "Radeon RX 9070 XT 16GB",
    brand: "AMD",
    family: "AMD",
    priceUsd: 600,
    vramGb: 16,
    tdp: 304,
    lengthMm: 267,
    gaming: 84,
    creator: 70,
    ai: 50,
    cuda: false,
    blurb: "RDNA 4 的 1440p 卡。光柵強過它的 AI 定位。",
  },
];

const mobos: MoboPart[] = [
  {
    id: "mb-b650-matx",
    slot: "motherboard",
    name: "B650 Micro-ATX",
    brand: "AMD",
    family: "AMD",
    priceUsd: 130,
    socket: "AM5",
    chipset: "B650",
    form: "mATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 192,
    ratedSpeed: 6000,
    vrm: "entry",
    wifi: true,
    blurb: "精巧 AM5 板。65–120 W 沒問題，跳過 170 W 旗艦。",
  },
  {
    id: "mb-b650e-atx",
    slot: "motherboard",
    name: "B650E ATX",
    brand: "AMD",
    family: "AMD",
    priceUsd: 180,
    socket: "AM5",
    chipset: "B650E",
    form: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 192,
    ratedSpeed: 6400,
    vrm: "mid",
    wifi: true,
    blurb: "耐操 AM5 ATX，GPU 走 PCIe 5.0。",
  },
  {
    id: "mb-x870-atx",
    slot: "motherboard",
    name: "X870 ATX",
    brand: "AMD",
    family: "AMD",
    priceUsd: 250,
    socket: "AM5",
    chipset: "X870",
    form: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 256,
    ratedSpeed: 6400,
    vrm: "mid",
    wifi: true,
    blurb: "較新 I/O 與 USB4。7800X3D／9700 級的合理歸宿。",
  },
  {
    id: "mb-x870e-atx",
    slot: "motherboard",
    name: "X870E ATX",
    brand: "AMD",
    family: "AMD",
    priceUsd: 380,
    socket: "AM5",
    chipset: "X870E",
    form: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 256,
    ratedSpeed: 8000,
    vrm: "high",
    wifi: true,
    blurb: "高階 VRM，扛得住 9950X 全核。",
  },
  {
    id: "mb-x870-itx",
    slot: "motherboard",
    name: "X870 Mini-ITX",
    brand: "AMD",
    family: "AMD",
    priceUsd: 290,
    socket: "AM5",
    chipset: "X870",
    form: "ITX",
    ramType: "DDR5",
    ramSlots: 2,
    maxRamGb: 96,
    ratedSpeed: 6400,
    vrm: "mid",
    wifi: true,
    blurb: "SFF AM5。只有兩槽，請用雙通道套條。",
  },
  {
    id: "mb-b760-matx",
    slot: "motherboard",
    name: "B760 Micro-ATX",
    brand: "Intel",
    family: "Intel",
    priceUsd: 130,
    socket: "LGA1700",
    chipset: "B760",
    form: "mATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 192,
    ratedSpeed: 5600,
    vrm: "entry",
    wifi: true,
    blurb: "上一代 Intel 小底板。配 14600K，別配 14900K。",
  },
  {
    id: "mb-z790-atx",
    slot: "motherboard",
    name: "Z790 ATX",
    brand: "Intel",
    family: "Intel",
    priceUsd: 250,
    socket: "LGA1700",
    chipset: "Z790",
    form: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 192,
    ratedSpeed: 7200,
    vrm: "high",
    wifi: true,
    blurb: "解鎖 14 代板，VRM 跟得上。",
  },
  {
    id: "mb-b860-atx",
    slot: "motherboard",
    name: "B860 ATX",
    brand: "Intel",
    family: "Intel",
    priceUsd: 180,
    socket: "LGA1851",
    chipset: "B860",
    form: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 256,
    ratedSpeed: 6400,
    vrm: "mid",
    wifi: true,
    blurb: "Arrow Lake 日常板。沒有 Z 功能，I/O 夠用。",
  },
  {
    id: "mb-z890-atx",
    slot: "motherboard",
    name: "Z890 ATX",
    brand: "Intel",
    family: "Intel",
    priceUsd: 320,
    socket: "LGA1851",
    chipset: "Z890",
    form: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 256,
    ratedSpeed: 8000,
    vrm: "high",
    wifi: true,
    blurb: "解鎖 Ultra 200 平台。265K／285K 請買這張。",
  },
];

const rams: RamPart[] = [
  {
    id: "ram-16-1x16",
    slot: "ram",
    name: "16GB DDR5-5600 (1x16)",
    brand: "Generic",
    family: "Other",
    priceUsd: 40,
    type: "DDR5",
    speed: 5600,
    capacityGb: 16,
    sticks: 1,
    cl: 36,
    blurb: "單通道陷阱。便宜，但效能會留在桌上。",
  },
  {
    id: "ram-16-2x8",
    slot: "ram",
    name: "16GB DDR5-5600 (2x8)",
    brand: "Generic",
    family: "Other",
    priceUsd: 50,
    type: "DDR5",
    speed: 5600,
    capacityGb: 16,
    sticks: 2,
    cl: 36,
    blurb: "雙通道 16 GB。文書夠，現代遊戲和 AI 偏少。",
  },
  {
    id: "ram-32-6000",
    slot: "ram",
    name: "32GB DDR5-6000 CL30 (2x16)",
    brand: "Generic",
    family: "Other",
    priceUsd: 95,
    type: "DDR5",
    speed: 6000,
    capacityGb: 32,
    sticks: 2,
    cl: 30,
    blurb: "AM5 甜點。幾乎每套遊戲機的預設。",
  },
  {
    id: "ram-32-6400",
    slot: "ram",
    name: "32GB DDR5-6400 CL32 (2x16)",
    brand: "Generic",
    family: "Other",
    priceUsd: 120,
    type: "DDR5",
    speed: 6400,
    capacityGb: 32,
    sticks: 2,
    cl: 32,
    blurb: "比 6000 快一點。AM5 上通常沒多少增益。",
  },
  {
    id: "ram-64-6000",
    slot: "ram",
    name: "64GB DDR5-6000 CL30 (2x32)",
    brand: "Generic",
    family: "Other",
    priceUsd: 190,
    type: "DDR5",
    speed: 6000,
    capacityGb: 64,
    sticks: 2,
    cl: 30,
    blurb: "創作／本地 AI 預設。分頁再加 7B 模型還塞得下。",
  },
  {
    id: "ram-96-5600",
    slot: "ram",
    name: "96GB DDR5-5600 (2x48)",
    brand: "Generic",
    family: "Other",
    priceUsd: 280,
    type: "DDR5",
    speed: 5600,
    capacityGb: 96,
    sticks: 2,
    cl: 40,
    blurb: "容量優先於時脈。重 VM、資料集和較大模型。",
  },
];

const ssds: SsdPart[] = [
  {
    id: "ssd-1tb-g4",
    slot: "ssd",
    name: "1TB NVMe Gen4",
    brand: "Generic",
    family: "Other",
    priceUsd: 70,
    capacityTb: 1,
    gen: "Gen4",
    blurb: "夠裝 Windows 和幾款遊戲。",
  },
  {
    id: "ssd-2tb-g4",
    slot: "ssd",
    name: "2TB NVMe Gen4",
    brand: "Generic",
    family: "Other",
    priceUsd: 120,
    capacityTb: 2,
    gen: "Gen4",
    blurb: "現在遊戲庫的甜點容量。",
  },
  {
    id: "ssd-2tb-g5",
    slot: "ssd",
    name: "2TB NVMe Gen5",
    brand: "Generic",
    family: "Other",
    priceUsd: 200,
    capacityTb: 2,
    gen: "Gen5",
    blurb: "大專案檔連續讀寫更快。也更熱。",
  },
  {
    id: "ssd-4tb-g4",
    slot: "ssd",
    name: "4TB NVMe Gen4",
    brand: "Generic",
    family: "Other",
    priceUsd: 240,
    capacityTb: 4,
    gen: "Gen4",
    blurb: "影片快取和模型權重，不必再搬硬碟。",
  },
];

const psus: PsuPart[] = [
  {
    id: "psu-550-br",
    slot: "psu",
    name: "550W 銅牌",
    brand: "Generic",
    family: "Other",
    priceUsd: 55,
    wattage: 550,
    efficiency: "Bronze",
    atx31: false,
    blurb: "只給文書／內顯。不要配現代獨顯。",
  },
  {
    id: "psu-650-g",
    slot: "psu",
    name: "650W 金牌",
    brand: "Generic",
    family: "Other",
    priceUsd: 85,
    wattage: 650,
    efficiency: "Gold",
    atx31: false,
    blurb: "蓋得住 4060 級。4070 Super 以上請跳過。",
  },
  {
    id: "psu-750-g",
    slot: "psu",
    name: "750W 金牌 ATX 3.1",
    brand: "Generic",
    family: "Other",
    priceUsd: 110,
    wattage: 750,
    efficiency: "Gold",
    atx31: true,
    blurb: "老實的 1440p 電源。40／50 系原生 12V-2×6。",
  },
  {
    id: "psu-850-g",
    slot: "psu",
    name: "850W 金牌 ATX 3.1",
    brand: "Generic",
    family: "Other",
    priceUsd: 140,
    wattage: 850,
    efficiency: "Gold",
    atx31: true,
    blurb: "4080／5080 級的安全選擇。",
  },
  {
    id: "psu-1000-g",
    slot: "psu",
    name: "1000W 金牌 ATX 3.1",
    brand: "Generic",
    family: "Other",
    priceUsd: 180,
    wattage: 1000,
    efficiency: "Gold",
    atx31: true,
    blurb: "4090 地帶。之後還能升級顯卡。",
  },
  {
    id: "psu-1200-p",
    slot: "psu",
    name: "1200W 白金 ATX 3.1",
    brand: "Generic",
    family: "Other",
    priceUsd: 250,
    wattage: 1200,
    efficiency: "Platinum",
    atx31: true,
    blurb: "給 5090 + 16 核。其他配置都過頭。",
  },
];

const coolers: CoolerPart[] = [
  {
    id: "cool-stock",
    slot: "cooler",
    name: "原廠盒裝散熱",
    brand: "Generic",
    family: "Other",
    priceUsd: 15,
    kind: "stock",
    tdpRating: 65,
    heightMm: 68,
    radiatorMm: null,
    blurb: "原廠風格式散熱。65 W 沒問題，再上去就沒了。",
  },
  {
    id: "cool-low",
    slot: "cooler",
    name: "矮塔風冷",
    brand: "Generic",
    family: "Other",
    priceUsd: 35,
    kind: "air",
    tdpRating: 95,
    heightMm: 47,
    radiatorMm: null,
    blurb: "ITX 求生款。壓不住 170 W 的 Ryzen 9。",
  },
  {
    id: "cool-tower",
    slot: "cooler",
    name: "單塔風冷",
    brand: "Generic",
    family: "Other",
    priceUsd: 40,
    kind: "air",
    tdpRating: 220,
    heightMm: 155,
    radiatorMm: null,
    blurb: "Peerless Assassin 這一級。預設風冷。",
  },
  {
    id: "cool-dual",
    slot: "cooler",
    name: "雙塔風冷",
    brand: "Generic",
    family: "Other",
    priceUsd: 90,
    kind: "air",
    tdpRating: 250,
    heightMm: 165,
    radiatorMm: null,
    blurb: "NH-D15 這一級。先量機殼高度，有些 mATX 太矮。",
  },
  {
    id: "cool-240",
    slot: "cooler",
    name: "240mm 一體式水冷",
    brand: "Generic",
    family: "Other",
    priceUsd: 90,
    kind: "aio",
    tdpRating: 250,
    heightMm: null,
    radiatorMm: 240,
    blurb: "多數中塔和不少 ITX 裝得下。120 W 很安靜。",
  },
  {
    id: "cool-360",
    slot: "cooler",
    name: "360mm 一體式水冷",
    brand: "Generic",
    family: "Other",
    priceUsd: 140,
    kind: "aio",
    tdpRating: 320,
    heightMm: null,
    radiatorMm: 360,
    blurb: "旗艦風冷或水冷。機殼必須真的能裝 360mm。",
  },
];

const cases: CasePart[] = [
  {
    id: "case-itx",
    slot: "case",
    name: "三明治 ITX",
    brand: "Generic",
    family: "Other",
    priceUsd: 140,
    supports: ["ITX"],
    gpuMaxMm: 305,
    coolerMaxMm: 72,
    radiators: [240],
    blurb: "SFF。ATX 板裝不進。長 4090 也裝不進。",
  },
  {
    id: "case-matx",
    slot: "case",
    name: "精巧 mATX",
    brand: "Generic",
    family: "Other",
    priceUsd: 75,
    supports: ["ITX", "mATX"],
    gpuMaxMm: 330,
    coolerMaxMm: 158,
    radiators: [240],
    blurb: "佔地小。雙塔風冷和 360 水冷不行。",
  },
  {
    id: "case-mid",
    slot: "case",
    name: "標準中塔",
    brand: "Generic",
    family: "Other",
    priceUsd: 90,
    supports: ["ITX", "mATX", "ATX"],
    gpuMaxMm: 380,
    coolerMaxMm: 165,
    radiators: [240, 360],
    blurb: "預設 ATX 機殼。這個目錄幾乎都裝得進。",
  },
  {
    id: "case-air",
    slot: "case",
    name: "高風流中塔",
    brand: "Generic",
    family: "Other",
    priceUsd: 120,
    supports: ["ITX", "mATX", "ATX"],
    gpuMaxMm: 420,
    coolerMaxMm: 175,
    radiators: [240, 360],
    blurb: "網狀前面板，GPU 淨空長。4090 友善款。",
  },
  {
    id: "case-full",
    slot: "case",
    name: "全塔",
    brand: "Generic",
    family: "Other",
    priceUsd: 180,
    supports: ["ITX", "mATX", "ATX"],
    gpuMaxMm: 450,
    coolerMaxMm: 190,
    radiators: [240, 360],
    blurb: "空間多到誇張。給 5090 工作站，不是給 4060。",
  },
];

export const PARTS: Part[] = [
  ...cpus,
  ...gpus,
  ...mobos,
  ...rams,
  ...ssds,
  ...psus,
  ...coolers,
  ...cases,
];

export const PARTS_BY_ID: Record<string, Part> = Object.fromEntries(
  PARTS.map((p) => [p.id, p]),
);

export function partsIn(slot: SlotId): Part[] {
  return PARTS.filter((p) => p.slot === slot);
}

export function getPart(id: string | undefined): Part | undefined {
  if (!id) return undefined;
  return PARTS_BY_ID[id];
}
